AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lex-factory.gemspec'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10
